-- [제약조건 중 외래키!]

-- 웹사이트에서 게시판과 이름  [참조하는] 게시판 댓글 테이블 구성
-- 게시판 테이블 : [작성자 / 게시판 글 내용 / 작성시간]
-- 댓글 테이블 : [작성자 / 댓글 내용 / 작성시간]

DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;
DROP TABLE BCOMMENT;
DROP SEQUENCE BCOMMNET_SEQ;

CREATE TABLE BOARD(
    B_NO NUMBER(4) PRIMARY KEY,
    B_NAME VARCHAR2(10 CHAR) NOT NULL,
    B_COMMENT VARCHAR2(100 CHAR) NOT NULL,
    B_TIME DATE NOT NULL
);

CREATE SEQUENCE BOARD_SEQ;
INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL, '진아', '오늘은 1월 2일', TO_DATE('2022-01-02 23:46:58', 'YYYY-DD-MM HH24:MI:SS'));
INSERT INTO BOARD VALUES (BOARD_SEQ.NEXTVAL, '지나', '내일은 1월 3일', TO_DATE('2022-01-02 23:46:58', 'YYYY-DD-MM HH24:MI:SS'));
SELECT * FROM BOARD;


CREATE TABLE BCOMMENT(
    C_NO NUMBER(4) PRIMARY KEY,
    C_NAME VARCHAR2(10 CHAR) NOT NULL,
    C_COMMNET VARCHAR2(100 CHAR) NOT NULL,
    C_TIME DATE NOT NULL,
    C_NUM NUMBER(4),
    CONSTRAINT FK_C_NUM FOREIGN KEY(C_NUM)      -- FK_뒤에 쓰는 말은 아무렇게 써줘도 돼유
        REFERENCES BOARD(b_NO)                  -- FK_ 를 앞뒤로 쓰는건 문화같은거얌!
        ON DELETE CASCADE
);

CREATE SEQUENCE BCOMMENT_SEQ;
INSERT INTO BCOMMENT VALUES (BOARD_SEQ.NEXTVAL, '도진', '낼 생각나야 하는데', SYSDATE , 1);
INSERT INTO BCOMMENT VALUES (BOARD_SEQ.NEXTVAL, '호진', '오늘은 1월 2일인데', SYSDATE, 2);
INSERT INTO BCOMMENT VALUES (BOARD_SEQ.NEXTVAL, '노진', '올해는 알차게 보내장', SYSDATE, 1);
INSERT INTO BCOMMENT VALUES (BOARD_SEQ.NEXTVAL, '모진', '지나화이팅', SYSDATE, 2);

SELECT * FROM BCOMMENT;

-- 게시글 1번을 지웠을 때 댓글도 같이 지워지는가?
DELETE FROM BOARD WHERE B_NO = 1;
--------------------------------------------------------------------------------